### ISSUE TITLE
Error: can't cd to /home/user/meteor-app/bundle/programs/server/

### ISSUE THREAD

**Issue by 0o-de-lally** [aedm/minimeteor#11] opened 2017-02-23 01:34 UTC
Running into an issue running the default build.

`/bin/sh: 1: cd: can't cd to /home/user/meteor-app/bundle/programs/server/`

Any advice?

**Comment by 0o-de-lally** [comment] 2017-02-23 02:53
BTW this is in Docker Cloud. In my case Docker Cloud builds successfully ( different than: https://github.com/aedm/minimeteor/issues/10 )

On Docker OSX and Rancher this image runs perfectly. Not sure why Docker Cloud is the exception. But I've had many issues with them.

**Comment by aedm** [comment] 2017-02-23 15:21
Thanks for reporting. Do you have a Dockerfile / repository for me to look at?

**Comment by 0o-de-lally** [comment] 2017-02-23 16:53
I don't have a public repo I can show. The dockerfile is literally only:
`
FROM aedm/minimeteor
`
Docker Cloud has many issues. But I was happy to see that this image at least was successfully built by the service. Have you had success on Docker Cloud?

**Comment by aedm** [comment] 2017-02-24 00:53
I tried Docker Hub, and MiniMeteor seems to work there. Do you have a build log?

**Comment by aedm** [comment] 2017-02-24 01:40
On Docker Cloud I got an error message, too. Can you maybe try using Docker Hub for automatic builds instead, and tell how it worked?

**Comment by 0o-de-lally** [comment] 2017-02-24 16:32
To be clear, the build works fine in Docker Cloud. It's the deployment of
the service that causes the issue.

**Comment by aedm** [comment] 2017-02-24 23:57
Can you share docker logs?
`$ docker logs myContainerName`

**Comment by 0o-de-lally** [comment] 2017-02-28 00:58
I'm not sure how to do that on Docker Cloud. The 'service' fails one second after starting the service. 

This is really all the info I have: https://www.dropbox.com/s/wm72j1pkjuk9hqe/Screenshot%202017-02-27%2019.56.17.png?dl=0

Do you know a way I can get more logs on Docker Cloud? Perhaps minimeteor could have a verbose mode? I'm not sure docker cloud would even show those logs.

**Comment by 0o-de-lally** [comment] 2017-03-03 16:44
@aedm I got the following response from Docker Cloud support. Does this make sense to you?

__________________

The reason that "cd" is failing is because the path is incorrect. If you'll take a look here you can see that once in the container you have no /home directory:

...$ docker run -ti --entrypoint=bash username/dockerImage

user@829a420a306f:/app$ pwd
/app

user@0faeefe36f48:/app$ cd /home/user/meteor-app/bundle/programs/server/
bash: cd: /home/user/meteor-app/bundle/programs/server/: No such file or directory

user@829a420a306f:/app$ ls -ll
total 48
-rw-r--r-- 1 root root 1131 Mar  3  2017 Dockerfile
-rw-r--r-- 1 root root 3078 Mar  3  2017 README.md
drwxr-xr-x 7 root root 4096 Mar  3  2017 client
drwxr-xr-x 2 root root 4096 Mar  3  2017 lib
-rw-r--r-- 1 root root  872 Mar  3  2017 mup.js
-rw-r--r-- 1 root root 3444 Mar  3  2017 package.json
drwxr-xr-x 3 root root 4096 Mar  3  2017 packages
drwxr-xr-x 3 root root 4096 Mar  3  2017 public
drwxr-xr-x 7 root root 4096 Mar  3  2017 server
-rw-r--r-- 1 root root  507 Mar  3  2017 settings-stage.json
-rw-r--r-- 1 root root  505 Mar  3  2017 settings.json
drwxr-xr-x 2 root root 4096 Mar  3  2017 tests

**Comment by aedm** [comment] 2017-03-05 14:11
Based on the build log, the build should have failed. The directory doesn't
exist because Meteor couldn't be installed. This still seems to be Docker
Cloud's fault, but I'll investigate further.

**Comment by 0o-de-lally** [comment] 2017-03-05 19:54
That makes sense, docker cloud may be giving a false positive result for
the build status.

**Comment by keyscores** [comment] 2017-03-08 21:03
@aedm I'm going to start writing a meteor guide using minimeteor: https://forums.meteor.com/t/docker-team-up-to-create-a-reference-docker-image-for-meteor/30829/89

It would be great if we could show it working on docker-cloud, since I think that's the easiest end-to-end solution for newbies.

I really want to make minimeteor the default in the community.

**Comment by 0o-de-lally** [comment] 2017-03-08 21:56
@aedm I'm going to start writing a meteor guide using minimeteor: https://forums.meteor.com/t/docker-team-up-to-create-a-reference-docker-image-for-meteor/30829/89

It would be great if we could show it working on docker-cloud, since I think that's the easiest end-to-end solution for newbies. 

The Docker Hub build works well, I've tested it on Rancher and Kubernetes and it works. It's only on Docker Cloud that the cd path seems to be breaking. Weird.

I really want to make minimeteor the default in the community. Thanks again!

**Comment by aedm** [comment] 2017-03-09 14:11
Hi, today I it seems to work. Maybe they changed something on Docker Cloud. Please retry your builds and make sure they aren't cached.

**Comment by 0o-de-lally** [comment] 2017-03-09 19:21
@aedm I'm still getting the error :(. 
Here's the image I'm testing against, it's the meteor Todos repo: https://hub.docker.com/r/keyscores/meteor-todos/

To be clear, it seems to run correctly on kubernetes, and on rancher. Only Docker Cloud has an issue.

Can you reproduce with this image?

**Comment by 0o-de-lally** [comment] 2017-03-09 19:42
@aedm  seems like I'm getting this locally on OSX as well:
```
docker run -d -e ROOT_URL=test -e MONGO_URL=test -p 80:3000 keyscores/meteor-todos
0f5e9bf5e006194168d7c5b711fc441d6a346bd2f1e52252366ff19444eb1d5c
$ docker ps -a

CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS                      PORTS               NAMES
0f5e9bf5e006        keyscores/meteor-todos   "/bin/sh -c 'cd /h..."   20 seconds ago      Exited (2) 17 seconds ago                       suspicious_noyce

$ docker logs suspicious_noyce
/bin/sh: 1: cd: can't cd to /home/user/meteor-app/bundle/programs/server/

```

**Comment by aedm** [comment] 2017-03-09 19:54
Can you show me the build logs on Docker Cloud?

**Comment by 0o-de-lally** [comment] 2017-03-09 20:03
Here are both of the build logs. 
Strangely now I'm getting the same error on both Quay.io builds, and Docker Cloud builds. Testing locally on OSX.

[docker-cloud build logs.txt](https://github.com/aedm/minimeteor/files/832155/docker-cloud.build.logs.txt)
[quayio build logs.txt](https://github.com/aedm/minimeteor/files/832156/quayio.build.logs.txt)

**Comment by aedm** [comment] 2017-03-09 20:07
That's the same issue, Meteor can't be installed. I'm afraid I can't do
anything about it. Can you create a Dockerfile (independent of MiniMeteor)
that successfully installs Meteor?

**Comment by 0o-de-lally** [comment] 2017-03-09 20:20
I see. 
Quay.io doesn't seem to be complaining about meteor. Is it also a false positive? 
I have had success with abernix/meteor, but it is also intermittent.

**Comment by 0o-de-lally** [comment] 2017-03-09 21:19
@aedm is there a way to include a command to make the build fail when meteor is not found. Currently I keep getting false positives for successful builds on Quay and Docker

**Comment by aedm** [comment] 2017-03-09 21:50
It's there. It should fail, but Docker Cloud simply ignores it. :-/

**Comment by 0o-de-lally** [comment] 2017-03-09 23:57
I'm having the same issue on Quay.io however. It's failing to install meteor, but marking the build successful.

**Comment by kizbitz** [comment] 2017-03-10 22:12
Hi @aedm & @keyscores,

I took a look at this today. As far as I can tell this doesn't seem to be an issue with this repository (minimeteor). I've set up an example project here: https://github.com/kizbitz/dockertest1 - this is building correctly as far as I can tell. See last 2 builds here: https://hub.docker.com/r/kizbitz/dockertest1/builds/ - (Note: Our Hub and Cloud service both use the same build backend)

If you pull/run with `docker run -it kizbitz/dockertest1` you'll get the error you'd expect (not passing in the ROOT_URL)

```
jbaker: )➤ docker run -ti kizbitz/dockertest1
/home/user/meteor-app/bundle/programs/server/node_modules/fibers/future.js:280
                                                throw(ex);
                                                ^

Error: Must pass options.rootUrl or set ROOT_URL in the server environment
    at Object.Meteor.absoluteUrl (packages/meteor.js:1268:11)
    at Object.WebAppInternals.generateBoilerplate (packages/webapp/webapp_server.js:556:20)
    at Object.main (packages/webapp/webapp_server.js:807:21)
    at /home/user/meteor-app/bundle/programs/server/boot.js:340:27
    at /home/user/meteor-app/bundle/programs/server/boot.js:354:5
    at Function.run (/home/user/meteor-app/bundle/programs/server/profile.js:510:12)
    at /home/user/meteor-app/bundle/programs/server/boot.js:351:
```
@keyscores - Could you test forking my repository, setting up an automated build from it, and see if it builds/runs correctly? - You can leave any issues/questions in your Docker support ticket.

Thanks,

Jerry

**Comment by aedm** [comment] 2017-03-10 23:43
@kizbitz Thanks for testing! That's exactly what should happen in case of a successful build. A while ago there was a difference between Cloud and Hub builds: it consistently failed on Cloud and passed on Hub. If those backends are in fact the same, there must have been something weird going on.

@keyscores I have no idea what's going on. I just tried a Docker Cloud build again, and it was successful.

**Comment by aedm** [comment] 2017-03-10 23:44
@keyscores Could you show me your GitHub repository that fails to build on Docker Cloud?

**Comment by 0o-de-lally** [comment] 2017-03-11 00:25
@kizbitz The image you provided is failing for me in docker cloud/hub, same as my previous images. 
Here's the build that fails:  https://hub.docker.com/r/keyscores/dockertest1/

Upon build  keyscores/dockertest1 shows a successful build, but it's a 'false positive'. Inspecting the logs you can see lots of errors :
".... Directory renamed before its status could be extracted"

Also when I deploy it, I get:
[dockertest1-eaf69b45-1]2017-03-10T22:00:29.773296471Z /bin/sh: 1: cd:
can't cd to /home/user/meteor-app/bundle/programs/server/

@kizbitz Could this be affecting a subset of users @ docker cloud? There are similar .tar extraction issues documented elsewhere.

**Comment by aedm** [comment] 2017-03-11 01:09
@keyscores I can confirm, for me @kizbitz's project also fails to build. This is weird.

**Comment by aedm** [comment] 2017-03-11 01:40
Another thing I noticed: if I use the small build servers (1G ram), Meteor install sometimes fails. If I use the large ones (3.75G ram), they succeed. Which is weird, since Meteor install is just a script copying some files. :-/

@kizbitz Which build configuration does Docker Hub use by default?

**Comment by kizbitz** [comment] 2017-03-14 20:52
Hi @aedm & @keyscores,

Apologize for the slow response. I was testing this issue with some of our backend build system engineers today. We have confirmed that using the small build instance for this build does cause failures on occasion with this project. Recommended solution is to upgrade the build node size or use your own builder node: https://docs.docker.com/docker-cloud/builds/automated-build/#set-up-builder-nodes

Note: Docker Hub uses the large instance size by default.

Thanks,

Jerry

**Comment by 0o-de-lally** [comment] 2017-03-14 21:15
@kizbitz Thanks for taking the time. 
I just tested this, and unfortunately in both cases (the Docker Cloud 'Large' build machine, and own node build) generate the same failure. See for example: keyscores/dockertest1-ownmachines

I'm wondering if it's possible you are seeing false positives. In my experience, you need to deploy the image to see the failure, since the Docker Cloud UI will show a 'false positive' success status.

**Comment by kizbitz** [comment] 2017-03-16 23:25
Hi @aedm & @keyscores,

Wanted to touch base and let you know that I'm still picking at this - I did get a couple failures on the large instance size - still trying to trace it through

Thanks,

Jerry

**Comment by 0o-de-lally** [comment] 2017-03-17 00:05
Thanks @kizbitz  glad to hear you could reproduce.

**Comment by aedm** [comment] 2017-03-17 09:47
@keyscores One thing I noticed before is that the error only occured when I used OverlayFS, but never on AUFS. Which driver does Docker Cloud use?

**Comment by kizbitz** [comment] 2017-03-17 16:38
Hi @aedm & @keyscores,

I've cloned the minimeteor repo and made the following changes:

- https://github.com/kizbitz/minimeteor/blob/master/docker/onbuild.sh#L2 - Verbose output and exit on errors/pipefail
- https://github.com/kizbitz/minimeteor/blob/master/docker/onbuild.sh#L52 (note on this below)

Prior to those changes the onbuild.sh script was not exiting with a non-zero exit code which caused the false positives.

---

Notes on the failures:

- Using the small instance sizes: Failures on every test - Usually running out of resources during tar extraction on the meteor install
- Using the large instance size I've had several good builds on two different accounts now except when the `apt-get purge` line is uncommented. When this line is uncommented the error here is:

```
Removing linux-libc-dev:amd64 ...
E: Sub-process returned an error code
```

I'm not sure what's going on here but I didn't research this error too much...

---

Could you set up an automated test build on my repository https://github.com/kizbitz/dockertest1 and ensure the following settings

- Large build instance size
- Disable the Build Caching
- Dockerfile location set to: `/`
- Build Context set to: `/testapp`

The Dockerfile and the Build Context settings are required otherwise the build will fail on the 'file not found error'

You _should_ get a successful build with these settings and when you run the `docker run -ti <namespace>/dockertest1` command you should see the ROOT_URL error instead of the 'file not found' error.

Thanks,

Jerry

**Comment by aedm** [comment] 2017-03-17 18:57
@kizbitz I tried your setup, and this far it seems to work. Thanks for all the effort you put into this. :)

I added your `set -exov` change to MiniMeteor to prevent false positives. Thanks for that, I didn't know about these flags. 

I can also confirm the strange error in the cleanup phase, so I added `set +exov` to ignore cleanup errors. The final image seems to work even if the cleanup phase fails. Weird bug though.

@keyscores: These changes are on the `development` branch at the moment, I'll merge it to `master` tomorrow. (My test server needs a few hours to test the shit out of it, and since it's St. Patrick's day, I already had two beers. Don't drink and merge, they say.)

**Comment by 0o-de-lally** [comment] 2017-03-17 18:58
Thanks @kizbitz It seems to be running on large instances. I'm perplexed though why a tar extraction would cause an overload. Any thoughts on that? Could be something for Meteor to look at.

@aedm Don't drink and merge :)  thanks

**Comment by 0o-de-lally** [comment] 2017-03-19 23:03
@aedm,  I just tested the latest build with my app on: quay.io, docker hub, and docker cloud. 
I'm getting failures on all three (quay.io has been quite reliable in the past). Seems like an NPM issue.
See quay.io and docker hub logs

[quayio logs 20170319.txt](https://github.com/aedm/minimeteor/files/853641/quayio.logs.20170319.txt)

[docker hub logs 20170319.txt](https://github.com/aedm/minimeteor/files/853642/docker.hub.logs.20170319.txt)

**Comment by 0o-de-lally** [comment] 2017-03-19 23:33
@kizbitz I'm trying your example build on docker hub, and I'm getting failures: https://hub.docker.com/r/keyscores/dockertest1.

You said these were the same instances as the "Large" Docker Cloud instances. Seems like a strange inconsistency...

**Comment by aedm** [comment] 2017-03-20 09:14
@keyscores: do those NPM errors occur locally if you execute a `docker build`? 
(By the way, I can't see your build logs on Docker Hub, only you have access to them.)

Yesterday I submitted @kizbitz's modifications to `master` to prevent false positive builds.

**Comment by kizbitz** [comment] 2017-03-20 14:04
@keyscores - Your error on hub was: `Build failed: Dockerfile not found at ./Dockerfile` - I changed your Dockerfile location in your Hub build settings to point to the correct directory and triggered another build that completed successfully.

As far as the NPM errors - Both of the Quay.io and the Docker build logs have the "ERR! Tried to download: ..." - These types of download errors do happen occasionally and usually triggering a rebuild will take care of it unless there happen to be issues in the upstream APT or NPM services/repositories at that particular time. 

@aedm - At this point I think you can close this issue. The original reported problem has been solved and now that you've added the verbose output and the exit on error most of the problems people will see should be able to be worked through on their end.

**Comment by aedm** [comment] 2017-03-22 20:30
I'm closing the issue then. Thanks for your efforts!

**Closed as completed by aedm** 2017-03-22 20:30 UTC
